const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel) => (payload) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld('pdv', {
  auth: {
    login: invoke('auth:login'),
    listActiveUsers: invoke('auth:listActiveUsers'),
    listAuditLog: invoke('auth:listAuditLog'),
    getSecurityConfig: invoke('auth:getSecurityConfig'),
    updateSecurityConfig: invoke('auth:updateSecurityConfig'),
    changeOwnPin: invoke('auth:changeOwnPin'),
  },
  products: {
    findByBarcode: invoke('product:findByBarcode'),
    findByBalancaCode: invoke('product:findByBalancaCode'),
    list: invoke('product:list'),
    count: invoke('product:count'),
    countConflitosCodigoBarrasPendentes: invoke('product:countConflitosCodigoBarrasPendentes'),
    findDuplicates: invoke('product:findDuplicates'),
    alertasDeMargem: invoke('product:alertasDeMargem'),
    aplicarDescontoValidade: invoke('product:aplicarDescontoValidade'),
    removerDescontoValidade: invoke('product:removerDescontoValidade'),
    findAlsoBoughtWith: invoke('product:findAlsoBoughtWith'),
    merge: invoke('product:merge'),
    listCategories: invoke('product:listCategories'),
    upsert: invoke('product:upsert'),
    deactivate: invoke('product:deactivate'),
    clearAll: invoke('product:clearAll'),
    generateInternalBarcode: invoke('product:generateInternalBarcode'),
    listPriceHistory: invoke('product:listPriceHistory'),
    listDailyMenu: invoke('product:listDailyMenu'),
    setFoto: invoke('product:setFoto'),
    removeFoto: invoke('product:removeFoto'),
    getFotoDataUrl: invoke('product:getFotoDataUrl'),
  },
  digitalMenu: {
    getConfig: invoke('digitalMenu:getConfig'),
    updateConfig: invoke('digitalMenu:updateConfig'),
    generateHtml: invoke('digitalMenu:generateHtml'),
    exportHtml: invoke('digitalMenu:exportHtml'),
    openInBrowser: invoke('digitalMenu:openInBrowser'),
  },
  weightBarcode: {
    getConfig: invoke('weightBarcode:getConfig'),
    updateConfig: invoke('weightBarcode:updateConfig'),
    parse: invoke('weightBarcode:parse'),
    listFormatos: invoke('weightBarcode:listFormatos'),
  },
  scaleHardware: {
    getConfig: invoke('scaleHardware:getConfig'),
    updateConfig: invoke('scaleHardware:updateConfig'),
    listPorts: invoke('scaleHardware:listPorts'),
    conectar: invoke('scaleHardware:conectar'),
    desconectar: invoke('scaleHardware:desconectar'),
    getLeituraAtual: invoke('scaleHardware:getLeituraAtual'),
  },
  stock: {
    getForLocation: invoke('stock:getForLocation'),
    listLowStock: invoke('stock:listLowStock'),
    listAlerts: invoke('stock:listAlerts'),
    previsaoDeRuptura: invoke('stock:previsaoDeRuptura'),
    sugestoesDescontoValidade: invoke('stock:sugestoesDescontoValidade'),
    adjust: invoke('stock:adjust'),
  },
  sale: {
    open: invoke('sale:open'),
    getOrOpenCurrent: invoke('sale:getOrOpenCurrent'),
    listByRange: invoke('sale:listByRange'),
    listRecentlySold: invoke('sale:listRecentlySold'),
    setCustomer: invoke('sale:setCustomer'),
    redeemLoyaltyPoints: invoke('sale:redeemLoyaltyPoints'),
    applyManagerDiscount: invoke('sale:applyManagerDiscount'),
    removeManagerDiscount: invoke('sale:removeManagerDiscount'),
    setServiceCharge: invoke('sale:setServiceCharge'),
    addItem: invoke('sale:addItem'),
    addPayment: invoke('sale:addPayment'),
    removePayment: invoke('sale:removePayment'),
    setItemNote: invoke('sale:setItemNote'),
    setItemPerson: invoke('sale:setItemPerson'),
    setItemPrice: invoke('sale:setItemPrice'),
    editarHistorico: invoke('sale:editarHistorico'),
    finalize: invoke('sale:finalize'),
    cancelItem: invoke('sale:cancelItem'),
    needsManagerAuthForCancel: invoke('sale:needsManagerAuthForCancel'),
    getItemsDetail: invoke('sale:getItemsDetail'),
    excluirDoHistorico: invoke('sale:excluirDoHistorico'),
    reexibirNoHistorico: invoke('sale:reexibirNoHistorico'),
    cancel: invoke('sale:cancel'),
  },
  table: {
    list: invoke('table:list'),
    create: invoke('table:create'),
    delete: invoke('table:delete'),
    open: invoke('table:open'),
    getCart: invoke('table:getCart'),
    release: invoke('table:release'),
    markCleaned: invoke('table:markCleaned'),
    markReserved: invoke('table:markReserved'),
    cancelReservation: invoke('table:cancelReservation'),
    transfer: invoke('table:transfer'),
    updatePeople: invoke('table:updatePeople'),
    desocupar: invoke('table:desocupar'),
  },
  ingredient: {
    list: invoke('ingredient:list'),
    upsert: invoke('ingredient:upsert'),
    deactivate: invoke('ingredient:deactivate'),
    getRecipe: invoke('ingredient:getRecipe'),
    setRecipe: invoke('ingredient:setRecipe'),
    computeDishCost: invoke('ingredient:computeDishCost'),
  },
  waste: {
    suggestCost: invoke('waste:suggestCost'),
    register: invoke('waste:register'),
    list: invoke('waste:list'),
    getSummary: invoke('waste:getSummary'),
    getByDay: invoke('waste:getByDay'),
  },
  license: {
    check: invoke('license:check'),
    getStatus: invoke('license:getStatus'),
  },
  message: {
    getForDisplay: invoke('message:getForDisplay'),
    getMotivoBloqueio: invoke('message:getMotivoBloqueio'),
  },
  profile: {
    listAvailable: invoke('profile:listAvailable'),
    getActive: invoke('profile:getActive'),
    setActive: invoke('profile:setActive'),
    create: invoke('profile:create'),
    update: invoke('profile:update'),
    duplicate: invoke('profile:duplicate'),
    delete: invoke('profile:delete'),
  },
  settings: {
    get: invoke('settings:get'),
    updateLocationName: invoke('settings:updateLocationName'),
  },
  users: {
    listAll: invoke('user:listAll'),
    create: invoke('user:create'),
    setActive: invoke('user:setActive'),
    resetPin: invoke('user:resetPin'),
  },
  io: {
    exportProducts: invoke('io:exportProducts'),
    importProducts: invoke('io:importProducts'),
    prepararRevinculacaoCodigosBarras: invoke('io:prepararRevinculacaoCodigosBarras'),
    aplicarRevinculacaoCodigosBarras: invoke('io:aplicarRevinculacaoCodigosBarras'),
  },
  attachments: {
    add: invoke('attachment:add'),
    list: invoke('attachment:list'),
    remove: invoke('attachment:remove'),
  },
  ai: {
    getSettings: invoke('ai:getSettings'),
    updateSettings: invoke('ai:updateSettings'),
    extractAttachment: invoke('ai:extractAttachment'),
    summarizeSales: invoke('ai:summarizeSales'),
    askTutor: invoke('ai:askTutor'),
  },
  cash: {
    getOpenSession: invoke('cash:getOpenSession'),
    open: invoke('cash:open'),
    getSummary: invoke('cash:getSummary'),
    close: invoke('cash:close'),
    listClosedSessions: invoke('cash:listClosedSessions'),
    getClosedSessionsSummary: invoke('cash:getClosedSessionsSummary'),
  },
  fiscal: {
    getConfig: invoke('fiscal:getConfig'),
    updateConfig: invoke('fiscal:updateConfig'),
    emitirNFCe: invoke('fiscal:emitirNFCe'),
    reenviarNFCe: invoke('fiscal:reenviarNFCe'),
    listNfceForSale: invoke('fiscal:listNfceForSale'),
    livroDeControlados: invoke('fiscal:livroDeControlados'),
    selectCertificado: invoke('fiscal:selectCertificado'),
  },
  payment: {
    getConfig: invoke('payment:getConfig'),
    updateConfig: invoke('payment:updateConfig'),
    buildPixPayload: invoke('payment:buildPixPayload'),
  },
  time: {
    getStatus: invoke('time:getStatus'),
    getBrasiliaNow: invoke('time:getBrasiliaNow'),
    syncNow: invoke('time:syncNow'),
  },
  report: {
    exportSales: invoke('report:exportSales'),
    exportAudit: invoke('report:exportAudit'),
    exportPurchaseSuggestions: invoke('report:exportPurchaseSuggestions'),
    exportWaste: invoke('report:exportWaste'),
    getCustomerPurchase: invoke('report:getCustomerPurchase'),
    exportCustomerPurchase: invoke('report:exportCustomerPurchase'),
  },
  pdvRegistry: {
    getStatus: invoke('pdvRegistry:getStatus'),
  },
  posDisplay: {
    getConfig: invoke('posDisplay:getConfig'),
    updateConfig: invoke('posDisplay:updateConfig'),
  },
  salesSync: {
    getConsolidated: invoke('salesSync:getConsolidated'),
    getGroupHistory: invoke('salesSync:getGroupHistory'),
    pushTodoOHistorico: invoke('salesSync:pushTodoOHistorico'),
  },
  customers: {
    list: invoke('customer:list'),
    upsert: invoke('customer:upsert'),
    getCreditHistory: invoke('customer:getCreditHistory'),
    registrarPagamento: invoke('customer:registrarPagamento'),
    listQueSumiram: invoke('customer:listQueSumiram'),
    montarLinkReconquista: invoke('customer:montarLinkReconquista'),
  },
  pets: {
    listByCustomer: invoke('pet:listByCustomer'),
    upsert: invoke('pet:upsert'),
    deactivate: invoke('pet:deactivate'),
    listLembretesPendentes: invoke('pet:listLembretesPendentes'),
    montarLinkLembrete: invoke('pet:montarLinkLembrete'),
  },
  delivery: {
    listRoutes: invoke('delivery:listRoutes'),
    upsertRoute: invoke('delivery:upsertRoute'),
    deactivateRoute: invoke('delivery:deactivateRoute'),
    listVehicles: invoke('delivery:listVehicles'),
    upsertVehicle: invoke('delivery:upsertVehicle'),
    deactivateVehicle: invoke('delivery:deactivateVehicle'),
    listPersons: invoke('delivery:listPersons'),
    upsertPerson: invoke('delivery:upsertPerson'),
    deactivatePerson: invoke('delivery:deactivatePerson'),
    create: invoke('delivery:create'),
    assign: invoke('delivery:assign'),
    updateStatus: invoke('delivery:updateStatus'),
    list: invoke('delivery:list'),
    montarLinkStatus: invoke('delivery:montarLinkStatus'),
  },
  botOrders: {
    getConfig: invoke('botOrders:getConfig'),
    updateConfig: invoke('botOrders:updateConfig'),
    create: invoke('botOrders:create'),
    list: invoke('botOrders:list'),
    listActive: invoke('botOrders:listActive'),
    getWithItems: invoke('botOrders:getWithItems'),
    updateStatus: invoke('botOrders:updateStatus'),
    updateItemStatus: invoke('botOrders:updateItemStatus'),
    listInStockByCategory: invoke('botOrders:listInStockByCategory'),
  },
  whatsapp: {
    getStatus: invoke('whatsapp:getStatus'),
    connect: invoke('whatsapp:connect'),
    disconnect: invoke('whatsapp:disconnect'),
  },
  quotes: {
    create: invoke('quote:create'),
    addItem: invoke('quote:addItem'),
    removeItem: invoke('quote:removeItem'),
    get: invoke('quote:get'),
    list: invoke('quote:list'),
    cancel: invoke('quote:cancel'),
    convertToSale: invoke('quote:convertToSale'),
  },
  eyewear: {
    listByCustomer: invoke('eyewear:listByCustomer'),
    upsert: invoke('eyewear:upsert'),
    deactivate: invoke('eyewear:deactivate'),
  },
  appointments: {
    listProfessionals: invoke('appointment:listProfessionals'),
    upsertProfessional: invoke('appointment:upsertProfessional'),
    deactivateProfessional: invoke('appointment:deactivateProfessional'),
    create: invoke('appointment:create'),
    reschedule: invoke('appointment:reschedule'),
    updateStatus: invoke('appointment:updateStatus'),
    list: invoke('appointment:list'),
    montarLinkConfirmacao: invoke('appointment:montarLinkConfirmacao'),
  },
  loyalty: {
    getConfig: invoke('loyalty:getConfig'),
    updateConfig: invoke('loyalty:updateConfig'),
  },
  productSync: {
    buscarNoGrupo: invoke('productSync:buscarNoGrupo'),
    buscarNoGrupoPorCodigoBarras: invoke('productSync:buscarNoGrupoPorCodigoBarras'),
    importarDoGrupo: invoke('productSync:importarDoGrupo'),
    prepararRevinculacaoViaGrupo: invoke('productSync:prepararRevinculacaoViaGrupo'),
  },
  suppliers: {
    list: invoke('supplier:list'),
    upsert: invoke('supplier:upsert'),
    suggestPurchases: invoke('supplier:suggestPurchases'),
  },
  expenses: {
    create: invoke('expense:create'),
    markAsPaid: invoke('expense:markAsPaid'),
    list: invoke('expense:list'),
    listPending: invoke('expense:listPending'),
    remove: invoke('expense:remove'),
  },
  categories: {
    list: invoke('category:list'),
    create: invoke('category:create'),
    rename: invoke('category:rename'),
    remove: invoke('category:remove'),
    sugerirComIA: invoke('category:sugerirComIA'),
    aplicarSugestoes: invoke('category:aplicarSugestoes'),
  },
  returns: {
    findFinalizedSales: invoke('return:findFinalizedSales'),
    getSaleItems: invoke('return:getSaleItems'),
    create: invoke('return:create'),
    list: invoke('return:list'),
  },
  print: {
    receipt: invoke('print:receipt'),
    sendReceiptWhatsapp: invoke('print:sendReceiptWhatsapp'),
    label: invoke('print:label'),
    kitchenTicket: invoke('print:kitchenTicket'),
    dailyMenu: invoke('print:dailyMenu'),
    listPrinters: invoke('print:listPrinters'),
    testPage: invoke('print:testPage'),
    getReceiptConfig: invoke('print:getReceiptConfig'),
    updateReceiptConfig: invoke('print:updateReceiptConfig'),
  },
  dashboard: {
    getSummary: invoke('dashboard:getSummary'),
    listStaleProducts: invoke('dashboard:listStaleProducts'),
    getSalesByOperator: invoke('dashboard:getSalesByOperator'),
    getRelatorioProdutos: invoke('dashboard:getRelatorioProdutos'),
    getResultadoSimples: invoke('dashboard:getResultadoSimples'),
  },
  backup: {
    getStatus: invoke('backup:getStatus'),
    runNow: invoke('backup:runNow'),
    list: invoke('backup:list'),
    restore: invoke('backup:restore'),
    openFolder: invoke('backup:openFolder'),
    chooseSecondaryFolder: invoke('backup:chooseSecondaryFolder'),
  },
  supply: {
    pickAndExtract: invoke('supply:pickAndExtract'),
    confirmEntries: invoke('supply:confirmEntries'),
    getDraft: invoke('supply:getDraft'),
    saveDraft: invoke('supply:saveDraft'),
    clearDraft: invoke('supply:clearDraft'),
    listUpcomingExpiry: invoke('supply:listUpcomingExpiry'),
  },
  batches: {
    listForProduct: invoke('batch:listForProduct'),
  },
  update: {
    getStatus: invoke('update:getStatus'),
    getForcedStatus: invoke('update:getForcedStatus'),
    check: invoke('update:check'),
    download: invoke('update:download'),
    install: invoke('update:install'),
  },
  error: {
    report: invoke('error:report'),
  },
});
